swagger: "2.0"
info:
  description: "This is [O-MI Authorization](https://github.com/AaltoAsia/O-MI-Authorization/blob/master/README.md) reference implementation REST API."
  version: "1.0.0"
  title: "O-MI Authorization"
  #contact:
  #  email: ""
  #license:
  #  name: ""
  #  url: ""
host: "localhost"
basePath: "/v1"
tags:
- name: "Consumers"
  description: "Operations about consumers."
  #externalDocs:
  #  description: "Find out more"
  #  url: "http://swagger.io"
- name: "Groups/Roles"
  description: "Operations about groups."
- name: "Rules"
  description: "Operations about permission Rules."
  
consumes:
  - application/json
produces:
  - application/json

schemes:
- "http"
paths:
  /add-user:
    post:
      tags:
      - "Consumers"
      summary: "Add a new consumer"
      description: |
        Consumer consist of an identifier, which called `username` in the code.
        After adding, the consumer can be added to groups.

        **Note:** The consumer is automatically added to a group named
        `${username}_USERGROUP` and to the group `DEFAULT`.

      parameters:
      - in: "body"
        name: "body"
        description: "Parameters in json"
        required: true
        schema:
          $ref: "#/definitions/AddUser"
      responses:
        200:
          description: "OK"
        400:
          description: "Invalid input"
  /remove-user:
    post:
      tags:
      - "Consumers"
      summary: "Remove a consumer"
      description: |
        Consumer can be removed from the system. This also removes group
        `${username}_USERGROUP` and all other data that was connected to this
        consumer only.

      parameters:
      - in: "body"
        name: "body"
        description: "Parameters in json"
        required: true
        schema:
          $ref: "#/definitions/RemoveUser"
      responses:
        200:
          description: "OK"
        400:
          description: "Invalid input"
  /add-group:
    post:
      tags:
      - "Groups/Roles"
      summary: "Add a new group/role"
      description: |
        Creates a new empty group/role.
        A group can be connected to multiple consumers with
        [join-groups](#operation--join-groups-post).  This system does not
        impose any particular way of how to use groups. They can be thought as
        roles instead. To understand how the permissions combine when belonging
        to many groups, see
        [get-permissions](#operation--get-permissions-post).

      parameters:
      - in: "body"
        name: "body"
        description: "Parameters in json"
        required: true
        schema:
          $ref: "#/definitions/AddGroup"
      responses:
        200:
          description: "OK"
        400:
          description: "Invalid input"
  /remove-group:
    post:
      tags:
      - "Groups/Roles"
      summary: "Remove group"
      description: |
        Removes the group and removes all data that was connected to the group,
        including rules.

      parameters:
      - in: "body"
        name: "body"
        description: "Parameters in json"
        required: true
        schema:
          $ref: "#/definitions/RemoveGroup"
      responses:
        200:
          description: "OK"
        400:
          description: "Invalid input"
  /join-groups:
    post:
      tags:
      - "Groups/Roles"
      summary: "Add consumer to groups / assign roles"
      description: |
        Connects a consumer to one or more groups/roles.

        To understand how the permissions combine when belonging to many
        groups, see [get-permissions](#operation--get-permissions-post).
      parameters:
      - in: "body"
        name: "body"
        description: "Parameters in json"
        required: true
        schema:
          $ref: "#/definitions/JoinGroups"
      responses:
        200:
          description: "OK"
        400:
          description: "Invalid input"
  /leave-groups:
    post:
      tags:
      - "Groups/Roles"
      summary: "Remove consumer from groups / unassign roles"
      description: |
        Removes a connection from a consumer to one or more groups/roles.

      parameters:
      - in: "body"
        name: "body"
        description: "Parameters in json"
        required: true
        schema:
          $ref: "#/definitions/LeaveGroups"
      responses:
        200:
          description: "OK"
        400:
          description: "Invalid input"
          
  /set-rules:
    post:
      tags:
      - "Rules"
      summary: "Set rules for group/role"
      description: |
        Set permission rules for a group/role. These are seperated in allow and
        deny rules. In O-MI Node the rules are prosessed by first filtering the
        incoming request by allow rules and then filtering with the deny rules from
        the result.

        To set rules for consumer, it either needs to be added to groups or the
        automatic `username_USERGROUP` can be used.

      parameters:
      - in: "body"
        name: "body"
        description: "Parameters in json"
        required: true
        schema:
          $ref: "#/definitions/SetRules"
      responses:
        200:
          description: "OK"
        400:
          description: "Invalid input"
  /remove-rules:
    post:
      tags:
      - "Rules"
      summary: "Remove rules from group/role"
      description: ""

      parameters:
      - in: "body"
        name: "body"
        description: "Parameters in json"
        required: true
        schema:
          $ref: "#/definitions/RemoveRules"
      responses:
        200:
          description: "OK"
        400:
          description: "Invalid input"
  /get-permissions:
    post:
      tags:
      - "Rules"
      summary: "Get rules of a consumer and a request type"
      description: |
        Permissions of a consumer for a request type. This operation should be
        used by O-MI Node for authorization, meaning the result is compatible
        with Authorization API service v2.

        If the consumer has connections to many groups/roles (with
        [join-groups](#operation--join-groups-post)) and they have many rules,
        the rules are concatenated in the following way:
        * allow rules are combined with set union
        * deny rules are combined with set intersection

        Hierarchical structure of the O-DF paths is taken into account when
        doing these set operations. This way the consumer, belonging to a
        certain group, can not lose any permissions in that group just by
        joining other groups.

      parameters:
      - in: "body"
        name: "body"
        description: |
          Parameters in json.
        required: true
        schema:
          $ref: "#/definitions/GetPermissions"
      responses:
        200:
          description: "Rules aggregated for given consumer and request"
          schema:
            $ref: "#/definitions/PermissionResult"
        400:
          description: "Invalid input"
definitions:
  Request:
    type: string
    enum: [r, w, c, d]
    example: "w"
    description: |
      Select one or more requests:
      * `r` for read request
      * `w` for write request
      * `c` for call request
      * `d` for delete request

      When setting new rules, many request types can be used by concatenating them.

  GetPermissions:
    description: >
      Permissions of a consumer for a request type. This operation is used by O-MI Node 
      for authorization.
    type: object
    required:
      - username
      - request
    properties:
      username: &username
        type: string
        example: "Alice"
        description: "Consumer identifier to be used for this operation"
      request:
        $ref: "#/definitions/Request"

  PermissionResult:
    type: object 
    reqired:
      - allowed
      - denied
    properties:
      allowed:
        type: array 
        items: &path
          type: string 
          description: "O-DF path in the slash format `/Objects/MyObject/MyInfoItem`."
          example: "/Objects/MyObject/MyInfoItem"
        description: "Paths that are allowed for the consumer."
      denied: 
        type: array 
        items: *path
        description: "Paths that are disallowed for the consumer."

  Rule:
    type: object
    required:
      - path
      - allow
      - request
    properties:
      path: *path
      allow: &allow
        type: boolean
        example: true
        description: "Set to `true` to make an allow rule or `false` to make a deny rule."
      request:
        $ref: "#/definitions/Request"

  SetRules:
    type: object
    required:
      - group
      - rules
    properties:
      group: &groupname
        type: string
        description: "Group/Role identifier to be used in this operation."
        example: "Administrators"
      rules:
        type: array
        items:
          $ref: "#/definitions/Rule"

  RRule:
    type: object
    required:
      - path
      - allow
    properties:
      path: *path
      allow: *allow

  RemoveRules:
    type: object
    required:
      - group
      - rules
    properties:
      group: *groupname
      rules:
        type: array
        items:
          $ref: "#/definitions/RRule"

  AddUser:
    type: object
    required:
      - username
    properties:
      username: *username

  RemoveUser:
    $ref: "#/definitions/AddUser"

  AddGroup:
    type: object
    required:
      - groupname
    properties:
      groupname: *groupname

  RemoveGroup:
    $ref: "#/definitions/AddGroup"

  JoinGroups:
    type: object
    required:
      - username
      - groups
    properties:
      username: *username
      groups:
        type: array
        items: *groupname
        description: "List of group/role identifiers to be used in this operation."

  LeaveGroups:
    $ref: "#/definitions/JoinGroups"

